services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masad123
      POSTGRES_DB: pern_ecommerce_db
    volumes:
      - db_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: masadrayan2002@gmail.com
      PGADMIN_DEFAULT_PASSWORD: masad123
    depends_on:
      - db

volumes:
  db_data:
